### ISSUE TITLE
Unable to log into the site

### ISSUE THREAD

**Issue by superusercode** [cvweiss/skillq#56]
Logging in gives me this error, which my friends cannot reproduce: 
```
Slim Application Error
The application could not run because of the following error:

Details
Message: Unable to connect to database!
File: /var/www/skillq.net/vendor/cvweiss/zlibrary/src/Db.php
Line: 54
Trace
#0 /var/www/skillq.net/vendor/cvweiss/zlibrary/src/Db.php(201): Db::getPDO()
#1 /var/www/skillq.net/view/ccp-callback.php(27): Db::execute()
#2 /var/www/skillq.net/routes.php(94): include('/var/www/skillq...')
#3 [internal function]: {closure}()
#4 /var/www/skillq.net/vendor/slim/slim/Slim/Router.php(200): call_user_func_array()
#5 /var/www/skillq.net/vendor/slim/slim/Slim/Slim.php(1218): Slim\Router->dispatch()
#6 /var/www/skillq.net/vendor/slim/slim/Slim/Middleware/Flash.php(86): Slim\Slim->call()
#7 /var/www/skillq.net/vendor/slim/slim/Slim/Middleware/MethodOverride.php(94): Slim\Middleware\Flash->call()
#8 /var/www/skillq.net/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#9 /var/www/skillq.net/vendor/slim/slim/Slim/Slim.php(1167): Slim\Middleware\PrettyExceptions->call()
#10 /var/www/skillq.net/index.php(38): Slim\Slim->run()
#11 /var/www/skillq.net/public/index.php(3): require_once('/var/www/skillq...')
#12 {main}
```

It happens to me consistently no matter how or what I use to log in.

**Comment by cvweiss** [comment]
Please give it another shot.

**Comment by superusercode** [comment]
@cvweiss I no longer have the issue, thank you.
